---
version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
    - build:
        filters:
          branches:
            only:
              - master
        matrix:
          parameters:
            package:
            - linuxRpi3
            - linuxRpi4
            - linuxRpi5
            - raspberrypiWirelessFirmware
            - raspberrypifw
orbs:
  nix: eld/nix@1.1.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2023.07.1
    parameters:
      package:
        type: string
    resource_class: arm.large
    steps:
      - nix/install:
          channels: nixpkgs=https://nixos.org/channels/nixos-23.11
          extra-conf: |
            experimental-features = flakes nix-command
            cores = 0
            max-jobs = auto
      - nix/install-cachix
      - checkout
      - run:
          name: Setup Cachix repos
          command: |
            cachix use nix-community
            cachix use nix-rpi-kernels
            ./.ci/list-paths.sh > /tmp/store-path-pre-build
      - run:
          name: Build system
          command: |
            nix build '.#packages.aarch64-linux.<< parameters.package >>'
      - run:
          name: Push cache
          no_output_timeout: 60m # 10 mins are often not enough
          command: |
            ./.ci/push-paths.sh cachix "--compression-method xz --compression-level 9 --jobs 8" nix-rpi-kernels ""  ""
